services:
  mysql:
    image: mysql:8.4
    container_name: nysc-camp-evaluation-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nysc_camp_evaluation
    ports:
      - "3306:3306"
    volumes:
      - nysc_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  nysc_mysql_data:
